service: properties-backend

provider:
  name: aws
  stackName: ${self:service}-${self:provider.stage}
  runtime: nodejs20.x
  region: ${opt:region, env:AWS_REGION, 'eu-west-1'}
  stage: ${opt:stage, 'dev'}
  stackTags:
    Name: ${self:provider.stackName}
    AppGroup: properties
    AppRole: properties-service
    Environment: ${self:provider.stage}
  memorySize: 1024
  environment:
    SERVICE_STAGE: ${self:provider.stage}
    DATABASE_URL: ${env:DATABASE_URL, ''}

custom:
  serverless-offline:
    useChildProcesses: true
    httpPort: 3000
    host: 0.0.0.0
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    target: node20
    platform: node
  prune:
    automatic: true
    number: 5

functions:
  getProperties:
    handler: src/functions/get-properties.handler
    events:
      - http:
          method: GET
          path: properties/
          cors: true

plugins:
  - serverless-esbuild
  - serverless-prune-plugin
  - serverless-offline

resources:
  - ${file(resources/resource.yml)}
