/** Generated from crawler SerbianMunicipality enum; ids match DB location column. */
export interface MunicipalityOption { id: number; label: string }
export const MUNICIPALITY_OPTIONS: MunicipalityOption[] = [
  { id: 1, label: "Ada" },
  { id: 2, label: "Aleksandrovac" },
  { id: 3, label: "Aleksinac" },
  { id: 4, label: "Alibunar" },
  { id: 5, label: "Apatin" },
  { id: 6, label: "Arandjelovac" },
  { id: 7, label: "Arilje" },
  { id: 8, label: "Babusnica" },
  { id: 12, label: "Bač" },
  { id: 13, label: "Bačka Palanka" },
  { id: 14, label: "Bačka Topola" },
  { id: 15, label: "Bački Petrovac" },
  { id: 9, label: "Bajina Bašta" },
  { id: 10, label: "Barajevo" },
  { id: 11, label: "Batocina" },
  { id: 20, label: "Bečej" },
  { id: 16, label: "Bela Crkva" },
  { id: 17, label: "Bela Palanka" },
  { id: 19, label: "Beočin" },
  { id: 18, label: "Beograd" },
  { id: 21, label: "Blace" },
  { id: 22, label: "Bogatic" },
  { id: 23, label: "Bojnik" },
  { id: 24, label: "Boljevac" },
  { id: 25, label: "Bor" },
  { id: 26, label: "Bosilegrad" },
  { id: 27, label: "Brus" },
  { id: 28, label: "Bujanovac" },
  { id: 155, label: "Čačak" },
  { id: 154, label: "Čajetina" },
  { id: 152, label: "Ćićevac" },
  { id: 156, label: "Čoka" },
  { id: 29, label: "Crna Trava" },
  { id: 30, label: "Crveni Krst (Niš)" },
  { id: 157, label: "Čukarica" },
  { id: 153, label: "Ćuprija" },
  { id: 31, label: "Despotovac" },
  { id: 32, label: "Dimitrovgrad" },
  { id: 33, label: "Doljevac" },
  { id: 34, label: "Gadžin Han" },
  { id: 35, label: "Golubac" },
  { id: 36, label: "Gornji Milanovac" },
  { id: 37, label: "Grocka" },
  { id: 38, label: "Indjija" },
  { id: 39, label: "Irig" },
  { id: 40, label: "Ivanjica" },
  { id: 41, label: "Jagodina" },
  { id: 42, label: "Kanjiza" },
  { id: 43, label: "Kikinda" },
  { id: 44, label: "Kladovo" },
  { id: 45, label: "Knic" },
  { id: 46, label: "Knjaževac" },
  { id: 47, label: "Koceljeva" },
  { id: 48, label: "Kosjeric" },
  { id: 49, label: "Kovacica" },
  { id: 50, label: "Kovin" },
  { id: 51, label: "Kragujevac" },
  { id: 52, label: "Kraljevo" },
  { id: 53, label: "Krupanj" },
  { id: 54, label: "Krusevac" },
  { id: 57, label: "Kucevo" },
  { id: 55, label: "Kula" },
  { id: 56, label: "Kursumlija" },
  { id: 58, label: "Lajkovac" },
  { id: 59, label: "Lapovo" },
  { id: 60, label: "Lazarevac" },
  { id: 61, label: "Lebane" },
  { id: 62, label: "Leskovac" },
  { id: 63, label: "Ljig" },
  { id: 64, label: "Ljubovija" },
  { id: 65, label: "Loznica" },
  { id: 66, label: "Lucani" },
  { id: 67, label: "Majdanpek" },
  { id: 68, label: "Mali Idjos" },
  { id: 69, label: "Mali Zvornik" },
  { id: 70, label: "Malo Crnice" },
  { id: 71, label: "Medijana" },
  { id: 72, label: "Medvedja" },
  { id: 73, label: "Merosina" },
  { id: 74, label: "Mionica" },
  { id: 75, label: "Mladenovac" },
  { id: 76, label: "Negotin" },
  { id: 77, label: "Niš" },
  { id: 78, label: "Niška Banja" },
  { id: 79, label: "Nova Crnja" },
  { id: 80, label: "Nova Varos" },
  { id: 82, label: "Novi Bečej" },
  { id: 81, label: "Novi Beograd" },
  { id: 83, label: "Novi Kneževac" },
  { id: 84, label: "Novi Pazar" },
  { id: 85, label: "Novi Sad" },
  { id: 86, label: "Obrenovac" },
  { id: 87, label: "Odžaci" },
  { id: 88, label: "Opovo" },
  { id: 89, label: "Osečina" },
  { id: 91, label: "Palilula (Beograd)" },
  { id: 90, label: "Palilula (Niš)" },
  { id: 93, label: "Pancevo" },
  { id: 92, label: "Pantelej" },
  { id: 94, label: "Paracin" },
  { id: 96, label: "Pecinci" },
  { id: 95, label: "Petrovac" },
  { id: 97, label: "Pirot" },
  { id: 98, label: "Plandiste" },
  { id: 99, label: "Požega" },
  { id: 100, label: "Presevo" },
  { id: 101, label: "Priboj" },
  { id: 102, label: "Prijepolje" },
  { id: 103, label: "Prokuplje" },
  { id: 105, label: "Rača" },
  { id: 104, label: "Rakovica" },
  { id: 106, label: "Raška" },
  { id: 107, label: "Razanj" },
  { id: 108, label: "Rekovac" },
  { id: 109, label: "Ruma" },
  { id: 158, label: "Šabac" },
  { id: 110, label: "Savski Venac" },
  { id: 112, label: "Sečanj" },
  { id: 111, label: "Senta" },
  { id: 159, label: "Šid" },
  { id: 113, label: "Sjenica" },
  { id: 114, label: "Smederevo" },
  { id: 115, label: "Smederevska Palanka" },
  { id: 116, label: "Sokobanja" },
  { id: 117, label: "Sombor" },
  { id: 118, label: "Sopot" },
  { id: 119, label: "Srbobran" },
  { id: 120, label: "Sremska Mitrovica" },
  { id: 121, label: "Sremski Karlovci" },
  { id: 122, label: "Stara Pazova" },
  { id: 123, label: "Stari Grad (Beograd)" },
  { id: 124, label: "Subotica" },
  { id: 126, label: "Surčin" },
  { id: 125, label: "Surdulica" },
  { id: 127, label: "Svilajnac" },
  { id: 128, label: "Svrljig" },
  { id: 129, label: "Temerin" },
  { id: 130, label: "Titel" },
  { id: 131, label: "Topola" },
  { id: 132, label: "Trgoviste" },
  { id: 133, label: "Trstenik" },
  { id: 134, label: "Tutin" },
  { id: 135, label: "Ub" },
  { id: 136, label: "Valjevo" },
  { id: 137, label: "Varvarin" },
  { id: 138, label: "Velika Plana" },
  { id: 139, label: "Veliko Gradiste" },
  { id: 141, label: "Vladicin Han" },
  { id: 140, label: "Vladimirci" },
  { id: 142, label: "Vlasotince" },
  { id: 143, label: "Vozdovac" },
  { id: 144, label: "Vracar" },
  { id: 145, label: "Vrbas" },
  { id: 146, label: "Vrnjačka Banja" },
  { id: 147, label: "Vrsac" },
  { id: 160, label: "Žabalj" },
  { id: 161, label: "Žabari" },
  { id: 162, label: "Žagubica" },
  { id: 148, label: "Zaječar" },
  { id: 149, label: "Zemun" },
  { id: 163, label: "Žitište" },
  { id: 164, label: "Žitorađa" },
  { id: 150, label: "Zrenjanin" },
  { id: 151, label: "Zvezdara" },
]
