/**
 * Serbian municipalities and cities (LAU units per Serbian law, excl. Kosovo table on Wikipedia).
 * Values are stable integers for DB storage; do not reorder existing members.
 */
export enum SerbianMunicipality {
    UNKNOWN = 0,
    ADA_SERBIA = 1,
    ALEKSANDROVAC = 2,
    ALEKSINAC = 3,
    ALIBUNAR = 4,
    APATIN = 5,
    ARANDJELOVAC = 6,
    ARILJE = 7,
    BABUSNICA = 8,
    BAJINA_BASTA = 9,
    BARAJEVO = 10,
    BATOCINA = 11,
    BAC_SERBIA = 12,
    BACKA_PALANKA = 13,
    BACKA_TOPOLA = 14,
    BACKI_PETROVAC = 15,
    BELA_CRKVA = 16,
    BELA_PALANKA = 17,
    BELGRADE = 18,
    BEOCIN = 19,
    BECEJ = 20,
    BLACE = 21,
    BOGATIC = 22,
    BOJNIK_SERBIA = 23,
    BOLJEVAC = 24,
    BOR_SERBIA = 25,
    BOSILEGRAD = 26,
    BRUS = 27,
    BUJANOVAC = 28,
    CRNA_TRAVA = 29,
    CRVENI_KRST_NIS = 30,
    DESPOTOVAC = 31,
    DIMITROVGRAD_SERBIA = 32,
    DOLJEVAC = 33,
    GADZIN_HAN = 34,
    GOLUBAC = 35,
    GORNJI_MILANOVAC = 36,
    GROCKA = 37,
    INDJIJA = 38,
    IRIG_SERBIA = 39,
    IVANJICA = 40,
    JAGODINA = 41,
    KANJIZA = 42,
    KIKINDA = 43,
    KLADOVO = 44,
    KNIC = 45,
    KNJAZEVAC = 46,
    KOCELJEVA = 47,
    KOSJERIC = 48,
    KOVACICA = 49,
    KOVIN = 50,
    KRAGUJEVAC = 51,
    KRALJEVO = 52,
    KRUPANJ = 53,
    KRUSEVAC = 54,
    KULA_SERBIA = 55,
    KURSUMLIJA = 56,
    KUCEVO = 57,
    LAJKOVAC = 58,
    LAPOVO = 59,
    LAZAREVAC = 60,
    LEBANE = 61,
    LESKOVAC = 62,
    LJIG = 63,
    LJUBOVIJA = 64,
    LOZNICA = 65,
    LUCANI = 66,
    MAJDANPEK = 67,
    MALI_IDJOS = 68,
    MALI_ZVORNIK = 69,
    MALO_CRNICE = 70,
    MEDIJANA = 71,
    MEDVEDJA = 72,
    MEROSINA = 73,
    MIONICA = 74,
    MLADENOVAC = 75,
    NEGOTIN = 76,
    NIS = 77,
    NISKA_BANJA = 78,
    NOVA_CRNJA = 79,
    NOVA_VAROS = 80,
    NEW_BELGRADE = 81,
    NOVI_BECEJ = 82,
    NOVI_KNEZEVAC = 83,
    NOVI_PAZAR = 84,
    NOVI_SAD = 85,
    OBRENOVAC = 86,
    ODZACI = 87,
    OPOVO = 88,
    OSECINA = 89,
    PALILULA_NIS = 90,
    PALILULA_BELGRADE = 91,
    PANTELEJ_NIS = 92,
    PANCEVO = 93,
    PARACIN = 94,
    PETROVAC_SERBIA = 95,
    PECINCI = 96,
    PIROT = 97,
    PLANDISTE = 98,
    POZEGA_SERBIA = 99,
    PRESEVO = 100,
    PRIBOJ = 101,
    PRIJEPOLJE = 102,
    PROKUPLJE = 103,
    RAKOVICA_BELGRADE = 104,
    RACA_SERBIA = 105,
    RASKA_TOWN = 106,
    RAZANJ = 107,
    REKOVAC = 108,
    RUMA = 109,
    SAVSKI_VENAC = 110,
    SENTA = 111,
    SECANJ = 112,
    SJENICA = 113,
    SMEDEREVO = 114,
    SMEDEREVSKA_PALANKA = 115,
    SOKOBANJA = 116,
    SOMBOR = 117,
    SOPOT_SERBIA = 118,
    SRBOBRAN = 119,
    SREMSKA_MITROVICA = 120,
    SREMSKI_KARLOVCI = 121,
    STARA_PAZOVA = 122,
    STARI_GRAD_BELGRADE = 123,
    SUBOTICA = 124,
    SURDULICA = 125,
    SURCIN = 126,
    SVILAJNAC = 127,
    SVRLJIG = 128,
    TEMERIN = 129,
    TITEL = 130,
    TOPOLA = 131,
    TRGOVISTE = 132,
    TRSTENIK_SERBIA = 133,
    TUTIN_SERBIA = 134,
    UB_SERBIA = 135,
    VALJEVO = 136,
    VARVARIN = 137,
    VELIKA_PLANA = 138,
    VELIKO_GRADISTE = 139,
    VLADIMIRCI = 140,
    VLADICIN_HAN = 141,
    VLASOTINCE = 142,
    VOZDOVAC = 143,
    VRACAR = 144,
    VRBAS_SERBIA = 145,
    VRNJACKA_BANJA = 146,
    VRSAC = 147,
    ZAJECAR = 148,
    ZEMUN = 149,
    ZRENJANIN = 150,
    ZVEZDARA = 151,
    CICEVAC = 152,
    CUPRIJA = 153,
    CAJETINA = 154,
    CACAK = 155,
    COKA = 156,
    CUKARICA = 157,
    SABAC = 158,
    SID = 159,
    ZABALJ = 160,
    ZABARI = 161,
    ZAGUBICA = 162,
    ZITISTE = 163,
    ZITORADJA = 164
}

function escapeRegExp(s: string): string {
    return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Normalize Serbian Latin for matching: đ→dj, dž/lj/nj digraphs, strip č/ć/š/ž marks, lowercase.
 */
export function foldSerbianLatin(s: string): string {
    let t = s
        .replace(/\u01C4/g, 'Dz')
        .replace(/\u01C5/g, 'Dz')
        .replace(/\u01C6/g, 'dz')
        .replace(/\u01F1/g, 'Dz')
        .replace(/\u01F2/g, 'Dz')
        .replace(/\u01F3/g, 'dz')
        .replace(/\u01CA/g, 'Nj')
        .replace(/\u01CB/g, 'Nj')
        .replace(/\u01CC/g, 'nj')
        .replace(/\u01C7/g, 'Lj')
        .replace(/\u01C8/g, 'Lj')
        .replace(/\u01C9/g, 'lj');
    return t
        .replace(/DŽ/g, 'Dz')
        .replace(/Dž/g, 'Dz')
        .replace(/dž/g, 'dz')
        .replace(/Đ/g, 'Dj')
        .replace(/đ/g, 'dj')
        .normalize('NFD')
        .replace(/\p{M}/gu, '')
        .toLowerCase();
}

/** Raw + generated aliases (ASCII); folded at build time together with {@link LOCATION_ALIAS_EXTRA}. */
const LOCATION_ALIAS_RAW: [string, SerbianMunicipality][] = [
    ['dimitrovgrad, serbia', SerbianMunicipality.DIMITROVGRAD_SERBIA],
    ['stari grad, belgrade', SerbianMunicipality.STARI_GRAD_BELGRADE],
    ['dimitrovgrad serbia', SerbianMunicipality.DIMITROVGRAD_SERBIA],
    ['smederevska palanka', SerbianMunicipality.SMEDEREVSKA_PALANKA],
    ['stari grad belgrade', SerbianMunicipality.STARI_GRAD_BELGRADE],
    ['dimitrovgradserbia', SerbianMunicipality.DIMITROVGRAD_SERBIA],
    ['palilula, belgrade', SerbianMunicipality.PALILULA_BELGRADE],
    ['rakovica, belgrade', SerbianMunicipality.RAKOVICA_BELGRADE],
    ['smederevskapalanka', SerbianMunicipality.SMEDEREVSKA_PALANKA],
    ['palilula belgrade', SerbianMunicipality.PALILULA_BELGRADE],
    ['petrovac (serbia)', SerbianMunicipality.PETROVAC_SERBIA],
    ['petrovac na mlavi', SerbianMunicipality.PETROVAC_SERBIA],
    ['rakovica belgrade', SerbianMunicipality.RAKOVICA_BELGRADE],
    ['sremska mitrovica', SerbianMunicipality.SREMSKA_MITROVICA],
    ['starigradbelgrade', SerbianMunicipality.STARI_GRAD_BELGRADE],
    ['crveni krst, nis', SerbianMunicipality.CRVENI_KRST_NIS],
    ['gornji milanovac', SerbianMunicipality.GORNJI_MILANOVAC],
    ['palilulabelgrade', SerbianMunicipality.PALILULA_BELGRADE],
    ['rakovicabelgrade', SerbianMunicipality.RAKOVICA_BELGRADE],
    ['sremskamitrovica', SerbianMunicipality.SREMSKA_MITROVICA],
    ['sremski karlovci', SerbianMunicipality.SREMSKI_KARLOVCI],
    ['trstenik, serbia', SerbianMunicipality.TRSTENIK_SERBIA],
    ['crveni krst nis', SerbianMunicipality.CRVENI_KRST_NIS],
    ['gornjimilanovac', SerbianMunicipality.GORNJI_MILANOVAC],
    ['petrovac serbia', SerbianMunicipality.PETROVAC_SERBIA],
    ['petrovacnamlavi', SerbianMunicipality.PETROVAC_SERBIA],
    ['sremskikarlovci', SerbianMunicipality.SREMSKI_KARLOVCI],
    ['trstenik serbia', SerbianMunicipality.TRSTENIK_SERBIA],
    ['veliko gradiste', SerbianMunicipality.VELIKO_GRADISTE],
    ['backi petrovac', SerbianMunicipality.BACKI_PETROVAC],
    ['bojnik, serbia', SerbianMunicipality.BOJNIK_SERBIA],
    ['petrovacserbia', SerbianMunicipality.PETROVAC_SERBIA],
    ['pozega, serbia', SerbianMunicipality.POZEGA_SERBIA],
    ['trstenikserbia', SerbianMunicipality.TRSTENIK_SERBIA],
    ['velikogradiste', SerbianMunicipality.VELIKO_GRADISTE],
    ['vrnjacka banja', SerbianMunicipality.VRNJACKA_BANJA],
    ['aleksandrovac', SerbianMunicipality.ALEKSANDROVAC],
    ['backa palanka', SerbianMunicipality.BACKA_PALANKA],
    ['backipetrovac', SerbianMunicipality.BACKI_PETROVAC],
    ['bojnik serbia', SerbianMunicipality.BOJNIK_SERBIA],
    ['crvenikrstnis', SerbianMunicipality.CRVENI_KRST_NIS],
    ['novi knezevac', SerbianMunicipality.NOVI_KNEZEVAC],
    ['palilula, nis', SerbianMunicipality.PALILULA_NIS],
    ['pantelej, nis', SerbianMunicipality.PANTELEJ_NIS],
    ['pozega serbia', SerbianMunicipality.POZEGA_SERBIA],
    ['sopot, serbia', SerbianMunicipality.SOPOT_SERBIA],
    ['tutin, serbia', SerbianMunicipality.TUTIN_SERBIA],
    ['vrbas, serbia', SerbianMunicipality.VRBAS_SERBIA],
    ['vrnjackabanja', SerbianMunicipality.VRNJACKA_BANJA],
    ['arandjelovac', SerbianMunicipality.ARANDJELOVAC],
    ['backa topola', SerbianMunicipality.BACKA_TOPOLA],
    ['backapalanka', SerbianMunicipality.BACKA_PALANKA],
    ['bajina basta', SerbianMunicipality.BAJINA_BASTA],
    ['bela palanka', SerbianMunicipality.BELA_PALANKA],
    ['bojnikserbia', SerbianMunicipality.BOJNIK_SERBIA],
    ['dimitrovgrad', SerbianMunicipality.DIMITROVGRAD_SERBIA],
    ['irig, serbia', SerbianMunicipality.IRIG_SERBIA],
    ['kula, serbia', SerbianMunicipality.KULA_SERBIA],
    ['mali zvornik', SerbianMunicipality.MALI_ZVORNIK],
    ['new belgrade', SerbianMunicipality.NEW_BELGRADE],
    ['novi beograd', SerbianMunicipality.NEW_BELGRADE],
    ['noviknezevac', SerbianMunicipality.NOVI_KNEZEVAC],
    ['palilula nis', SerbianMunicipality.PALILULA_NIS],
    ['pantelej nis', SerbianMunicipality.PANTELEJ_NIS],
    ['pozegaserbia', SerbianMunicipality.POZEGA_SERBIA],
    ['raca, serbia', SerbianMunicipality.RACA_SERBIA],
    ['raska (town)', SerbianMunicipality.RASKA_TOWN],
    ['savski venac', SerbianMunicipality.SAVSKI_VENAC],
    ['sopot serbia', SerbianMunicipality.SOPOT_SERBIA],
    ['stara pazova', SerbianMunicipality.STARA_PAZOVA],
    ['tutin serbia', SerbianMunicipality.TUTIN_SERBIA],
    ['velika plana', SerbianMunicipality.VELIKA_PLANA],
    ['vladicin han', SerbianMunicipality.VLADICIN_HAN],
    ['vrbas serbia', SerbianMunicipality.VRBAS_SERBIA],
    ['ada, serbia', SerbianMunicipality.ADA_SERBIA],
    ['bac, serbia', SerbianMunicipality.BAC_SERBIA],
    ['backatopola', SerbianMunicipality.BACKA_TOPOLA],
    ['bajinabasta', SerbianMunicipality.BAJINA_BASTA],
    ['belapalanka', SerbianMunicipality.BELA_PALANKA],
    ['bor, serbia', SerbianMunicipality.BOR_SERBIA],
    ['crveni krst', SerbianMunicipality.CRVENI_KRST_NIS],
    ['irig serbia', SerbianMunicipality.IRIG_SERBIA],
    ['kula serbia', SerbianMunicipality.KULA_SERBIA],
    ['malizvornik', SerbianMunicipality.MALI_ZVORNIK],
    ['malo crnice', SerbianMunicipality.MALO_CRNICE],
    ['newbelgrade', SerbianMunicipality.NEW_BELGRADE],
    ['niska banja', SerbianMunicipality.NISKA_BANJA],
    ['novibeograd', SerbianMunicipality.NEW_BELGRADE],
    ['palilulanis', SerbianMunicipality.PALILULA_NIS],
    ['pantelejnis', SerbianMunicipality.PANTELEJ_NIS],
    ['raca serbia', SerbianMunicipality.RACA_SERBIA],
    ['savskivenac', SerbianMunicipality.SAVSKI_VENAC],
    ['sopotserbia', SerbianMunicipality.SOPOT_SERBIA],
    ['starapazova', SerbianMunicipality.STARA_PAZOVA],
    ['tutinserbia', SerbianMunicipality.TUTIN_SERBIA],
    ['velikaplana', SerbianMunicipality.VELIKA_PLANA],
    ['vladicinhan', SerbianMunicipality.VLADICIN_HAN],
    ['vrbasserbia', SerbianMunicipality.VRBAS_SERBIA],
    ['ada serbia', SerbianMunicipality.ADA_SERBIA],
    ['bac serbia', SerbianMunicipality.BAC_SERBIA],
    ['bela crkva', SerbianMunicipality.BELA_CRKVA],
    ['bor serbia', SerbianMunicipality.BOR_SERBIA],
    ['bosilegrad', SerbianMunicipality.BOSILEGRAD],
    ['crna trava', SerbianMunicipality.CRNA_TRAVA],
    ['crvenikrst', SerbianMunicipality.CRVENI_KRST_NIS],
    ['despotovac', SerbianMunicipality.DESPOTOVAC],
    ['gadzin han', SerbianMunicipality.GADZIN_HAN],
    ['irigserbia', SerbianMunicipality.IRIG_SERBIA],
    ['kragujevac', SerbianMunicipality.KRAGUJEVAC],
    ['kulaserbia', SerbianMunicipality.KULA_SERBIA],
    ['kursumlija', SerbianMunicipality.KURSUMLIJA],
    ['mali idjos', SerbianMunicipality.MALI_IDJOS],
    ['malocrnice', SerbianMunicipality.MALO_CRNICE],
    ['mladenovac', SerbianMunicipality.MLADENOVAC],
    ['niskabanja', SerbianMunicipality.NISKA_BANJA],
    ['nova crnja', SerbianMunicipality.NOVA_CRNJA],
    ['nova varos', SerbianMunicipality.NOVA_VAROS],
    ['novi becej', SerbianMunicipality.NOVI_BECEJ],
    ['novi pazar', SerbianMunicipality.NOVI_PAZAR],
    ['prijepolje', SerbianMunicipality.PRIJEPOLJE],
    ['racaserbia', SerbianMunicipality.RACA_SERBIA],
    ['raska town', SerbianMunicipality.RASKA_TOWN],
    ['stari grad', SerbianMunicipality.STARI_GRAD_BELGRADE],
    ['ub, serbia', SerbianMunicipality.UB_SERBIA],
    ['vladimirci', SerbianMunicipality.VLADIMIRCI],
    ['vlasotince', SerbianMunicipality.VLASOTINCE],
    ['adaserbia', SerbianMunicipality.ADA_SERBIA],
    ['aleksinac', SerbianMunicipality.ALEKSINAC],
    ['babusnica', SerbianMunicipality.BABUSNICA],
    ['bacserbia', SerbianMunicipality.BAC_SERBIA],
    ['belacrkva', SerbianMunicipality.BELA_CRKVA],
    ['borserbia', SerbianMunicipality.BOR_SERBIA],
    ['bujanovac', SerbianMunicipality.BUJANOVAC],
    ['crnatrava', SerbianMunicipality.CRNA_TRAVA],
    ['gadzinhan', SerbianMunicipality.GADZIN_HAN],
    ['knjazevac', SerbianMunicipality.KNJAZEVAC],
    ['koceljeva', SerbianMunicipality.KOCELJEVA],
    ['lazarevac', SerbianMunicipality.LAZAREVAC],
    ['ljubovija', SerbianMunicipality.LJUBOVIJA],
    ['majdanpek', SerbianMunicipality.MAJDANPEK],
    ['maliidjos', SerbianMunicipality.MALI_IDJOS],
    ['novacrnja', SerbianMunicipality.NOVA_CRNJA],
    ['novavaros', SerbianMunicipality.NOVA_VAROS],
    ['novibecej', SerbianMunicipality.NOVI_BECEJ],
    ['novipazar', SerbianMunicipality.NOVI_PAZAR],
    ['obrenovac', SerbianMunicipality.OBRENOVAC],
    ['plandiste', SerbianMunicipality.PLANDISTE],
    ['prokuplje', SerbianMunicipality.PROKUPLJE],
    ['raskatown', SerbianMunicipality.RASKA_TOWN],
    ['smederevo', SerbianMunicipality.SMEDEREVO],
    ['sokobanja', SerbianMunicipality.SOKOBANJA],
    ['starigrad', SerbianMunicipality.STARI_GRAD_BELGRADE],
    ['surdulica', SerbianMunicipality.SURDULICA],
    ['svilajnac', SerbianMunicipality.SVILAJNAC],
    ['trgoviste', SerbianMunicipality.TRGOVISTE],
    ['ub serbia', SerbianMunicipality.UB_SERBIA],
    ['zitoradja', SerbianMunicipality.ZITORADJA],
    ['zrenjanin', SerbianMunicipality.ZRENJANIN],
    ['alibunar', SerbianMunicipality.ALIBUNAR],
    ['barajevo', SerbianMunicipality.BARAJEVO],
    ['batocina', SerbianMunicipality.BATOCINA],
    ['belgrade', SerbianMunicipality.BELGRADE],
    ['boljevac', SerbianMunicipality.BOLJEVAC],
    ['cajetina', SerbianMunicipality.CAJETINA],
    ['cukarica', SerbianMunicipality.CUKARICA],
    ['doljevac', SerbianMunicipality.DOLJEVAC],
    ['ivanjica', SerbianMunicipality.IVANJICA],
    ['jagodina', SerbianMunicipality.JAGODINA],
    ['kosjeric', SerbianMunicipality.KOSJERIC],
    ['kovacica', SerbianMunicipality.KOVACICA],
    ['kraljevo', SerbianMunicipality.KRALJEVO],
    ['krusevac', SerbianMunicipality.KRUSEVAC],
    ['lajkovac', SerbianMunicipality.LAJKOVAC],
    ['leskovac', SerbianMunicipality.LESKOVAC],
    ['medijana', SerbianMunicipality.MEDIJANA],
    ['medvedja', SerbianMunicipality.MEDVEDJA],
    ['merosina', SerbianMunicipality.MEROSINA],
    ['novi sad', SerbianMunicipality.NOVI_SAD],
    ['palilula', SerbianMunicipality.PALILULA_NIS],
    ['pantelej', SerbianMunicipality.PANTELEJ_NIS],
    ['rakovica', SerbianMunicipality.RAKOVICA_BELGRADE],
    ['srbobran', SerbianMunicipality.SRBOBRAN],
    ['subotica', SerbianMunicipality.SUBOTICA],
    ['trstenik', SerbianMunicipality.TRSTENIK_SERBIA],
    ['ubserbia', SerbianMunicipality.UB_SERBIA],
    ['varvarin', SerbianMunicipality.VARVARIN],
    ['vozdovac', SerbianMunicipality.VOZDOVAC],
    ['zagubica', SerbianMunicipality.ZAGUBICA],
    ['zvezdara', SerbianMunicipality.ZVEZDARA],
    ['beograd', SerbianMunicipality.BELGRADE],
    ['bogatic', SerbianMunicipality.BOGATIC],
    ['cicevac', SerbianMunicipality.CICEVAC],
    ['cuprija', SerbianMunicipality.CUPRIJA],
    ['golubac', SerbianMunicipality.GOLUBAC],
    ['indjija', SerbianMunicipality.INDJIJA],
    ['kanjiza', SerbianMunicipality.KANJIZA],
    ['kikinda', SerbianMunicipality.KIKINDA],
    ['kladovo', SerbianMunicipality.KLADOVO],
    ['krupanj', SerbianMunicipality.KRUPANJ],
    ['loznica', SerbianMunicipality.LOZNICA],
    ['mionica', SerbianMunicipality.MIONICA],
    ['negotin', SerbianMunicipality.NEGOTIN],
    ['novisad', SerbianMunicipality.NOVI_SAD],
    ['osecina', SerbianMunicipality.OSECINA],
    ['pancevo', SerbianMunicipality.PANCEVO],
    ['paracin', SerbianMunicipality.PARACIN],
    ['pecinci', SerbianMunicipality.PECINCI],
    ['presevo', SerbianMunicipality.PRESEVO],
    ['rekovac', SerbianMunicipality.REKOVAC],
    ['sjenica', SerbianMunicipality.SJENICA],
    ['svrljig', SerbianMunicipality.SVRLJIG],
    ['temerin', SerbianMunicipality.TEMERIN],
    ['valjevo', SerbianMunicipality.VALJEVO],
    ['zajecar', SerbianMunicipality.ZAJECAR],
    ['zitiste', SerbianMunicipality.ZITISTE],
    ['apatin', SerbianMunicipality.APATIN],
    ['arilje', SerbianMunicipality.ARILJE],
    ['beocin', SerbianMunicipality.BEOCIN],
    ['bojnik', SerbianMunicipality.BOJNIK_SERBIA],
    ['grocka', SerbianMunicipality.GROCKA],
    ['kucevo', SerbianMunicipality.KUCEVO],
    ['lapovo', SerbianMunicipality.LAPOVO],
    ['lebane', SerbianMunicipality.LEBANE],
    ['lucani', SerbianMunicipality.LUCANI],
    ['odzaci', SerbianMunicipality.ODZACI],
    ['pozega', SerbianMunicipality.POZEGA_SERBIA],
    ['priboj', SerbianMunicipality.PRIBOJ],
    ['razanj', SerbianMunicipality.RAZANJ],
    ['secanj', SerbianMunicipality.SECANJ],
    ['sombor', SerbianMunicipality.SOMBOR],
    ['surcin', SerbianMunicipality.SURCIN],
    ['topola', SerbianMunicipality.TOPOLA],
    ['vracar', SerbianMunicipality.VRACAR],
    ['zabalj', SerbianMunicipality.ZABALJ],
    ['zabari', SerbianMunicipality.ZABARI],
    ['becej', SerbianMunicipality.BECEJ],
    ['blace', SerbianMunicipality.BLACE],
    ['cacak', SerbianMunicipality.CACAK],
    ['kovin', SerbianMunicipality.KOVIN],
    ['opovo', SerbianMunicipality.OPOVO],
    ['pirot', SerbianMunicipality.PIROT],
    ['raska', SerbianMunicipality.RASKA_TOWN],
    ['sabac', SerbianMunicipality.SABAC],
    ['senta', SerbianMunicipality.SENTA],
    ['sopot', SerbianMunicipality.SOPOT_SERBIA],
    ['titel', SerbianMunicipality.TITEL],
    ['tutin', SerbianMunicipality.TUTIN_SERBIA],
    ['vrbas', SerbianMunicipality.VRBAS_SERBIA],
    ['vrsac', SerbianMunicipality.VRSAC],
    ['zemun', SerbianMunicipality.ZEMUN],
    ['brus', SerbianMunicipality.BRUS],
    ['coka', SerbianMunicipality.COKA],
    ['irig', SerbianMunicipality.IRIG_SERBIA],
    ['knic', SerbianMunicipality.KNIC],
    ['kula', SerbianMunicipality.KULA_SERBIA],
    ['ljig', SerbianMunicipality.LJIG],
    ['raca', SerbianMunicipality.RACA_SERBIA],
    ['ruma', SerbianMunicipality.RUMA],
    ['ada', SerbianMunicipality.ADA_SERBIA],
    ['bac', SerbianMunicipality.BAC_SERBIA],
    ['bor', SerbianMunicipality.BOR_SERBIA],
    ['nis', SerbianMunicipality.NIS],
    ['sid', SerbianMunicipality.SID],
    ['bg', SerbianMunicipality.BELGRADE],
    ['ub', SerbianMunicipality.UB_SERBIA],
];

/**
 * Extra aliases: Serbian Latin with č/ć/ž/š/đ/dž, common spellings, abbreviations.
 * All strings are folded when building {@link LOCATION_ALIAS_ENTRIES}.
 */
const LOCATION_ALIAS_EXTRA: [string, SerbianMunicipality][] = [
    ['Beograd', SerbianMunicipality.BELGRADE],
    ['Bečej', SerbianMunicipality.BECEJ],
    ['Novi Bečej', SerbianMunicipality.NOVI_BECEJ],
    ['Bačka Palanka', SerbianMunicipality.BACKA_PALANKA],
    ['Bačka Topola', SerbianMunicipality.BACKA_TOPOLA],
    ['Bački Petrovac', SerbianMunicipality.BACKI_PETROVAC],
    ['Bajina Bašta', SerbianMunicipality.BAJINA_BASTA],
    ['Aranđelovac', SerbianMunicipality.ARANDJELOVAC],
    ['Čačak', SerbianMunicipality.CACAK],
    ['Čoka', SerbianMunicipality.COKA],
    ['Čukarica', SerbianMunicipality.CUKARICA],
    ['Ćuprija', SerbianMunicipality.CUPRIJA],
    ['Ćićevac', SerbianMunicipality.CICEVAC],
    ['Šabac', SerbianMunicipality.SABAC],
    ['Šid', SerbianMunicipality.SID],
    ['Žabalj', SerbianMunicipality.ZABALJ],
    ['Žabari', SerbianMunicipality.ZABARI],
    ['Žagubica', SerbianMunicipality.ZAGUBICA],
    ['Žitište', SerbianMunicipality.ZITISTE],
    ['Žitorađa', SerbianMunicipality.ZITORADJA],
    ['Niš', SerbianMunicipality.NIS],
    ['Niška Banja', SerbianMunicipality.NISKA_BANJA],
    ['Pančevo', SerbianMunicipality.PANCEVO],
    ['Lučani', SerbianMunicipality.LUCANI],
    ['Inđija', SerbianMunicipality.INDJIJA],
    ['Kanjiža', SerbianMunicipality.KANJIZA],
    ['Mali Iđoš', SerbianMunicipality.MALI_IDJOS],
    ['Novi Kneževac', SerbianMunicipality.NOVI_KNEZEVAC],
    ['Kruševac', SerbianMunicipality.KRUSEVAC],
    ['Kuršumlija', SerbianMunicipality.KURSUMLIJA],
    ['Medveđa', SerbianMunicipality.MEDVEDJA],
    ['Osečina', SerbianMunicipality.OSECINA],
    ['Paraćin', SerbianMunicipality.PARACIN],
    ['Preševo', SerbianMunicipality.PRESEVO],
    ['Sečanj', SerbianMunicipality.SECANJ],
    ['Svrljig', SerbianMunicipality.SVRLJIG],
    ['Surčin', SerbianMunicipality.SURCIN],
    ['Voždovac', SerbianMunicipality.VOZDOVAC],
    ['Vračar', SerbianMunicipality.VRACAR],
    ['Vršac', SerbianMunicipality.VRSAC],
    ['Zaječar', SerbianMunicipality.ZAJECAR],
    ['Vrnjačka Banja', SerbianMunicipality.VRNJACKA_BANJA],
    ['Raška', SerbianMunicipality.RASKA_TOWN],
    ['Gadžin Han', SerbianMunicipality.GADZIN_HAN],
    ['Beočin', SerbianMunicipality.BEOCIN],
    ['Sremski Karlovci', SerbianMunicipality.SREMSKI_KARLOVCI],
    ['Novi Sad', SerbianMunicipality.NOVI_SAD],
    ['Novi Beograd', SerbianMunicipality.NEW_BELGRADE],
    ['Novi belgrade', SerbianMunicipality.NEW_BELGRADE],
    ['Stari Grad', SerbianMunicipality.STARI_GRAD_BELGRADE],
    ['Palilula', SerbianMunicipality.PALILULA_BELGRADE],
    ['Palilula BG', SerbianMunicipality.PALILULA_BELGRADE],
    ['Palilula Beograd', SerbianMunicipality.PALILULA_BELGRADE],
    ['Zemun', SerbianMunicipality.ZEMUN],
    ['Zvezdara', SerbianMunicipality.ZVEZDARA],
    ['Rakovica', SerbianMunicipality.RAKOVICA_BELGRADE],
    ['Savski Venac', SerbianMunicipality.SAVSKI_VENAC],
    ['Palilula Niš', SerbianMunicipality.PALILULA_NIS],
    ['Palilula Nisa', SerbianMunicipality.PALILULA_NIS],
    ['Pantelej', SerbianMunicipality.PANTELEJ_NIS],
    ['Crveni Krst', SerbianMunicipality.CRVENI_KRST_NIS],
    ['Medijana', SerbianMunicipality.MEDIJANA],
    ['ns', SerbianMunicipality.NOVI_SAD],
    ['n.s.', SerbianMunicipality.NOVI_SAD],
    ['bgd', SerbianMunicipality.BELGRADE],
    ['u Beogradu', SerbianMunicipality.BELGRADE],
    ['u Novom Sadu', SerbianMunicipality.NOVI_SAD],
    ['u Nišu', SerbianMunicipality.NIS],
    ['Veliko Gradište', SerbianMunicipality.VELIKO_GRADISTE],
    ['Knjaževac', SerbianMunicipality.KNJAZEVAC],
    ['Požega', SerbianMunicipality.POZEGA_SERBIA],
    ['Plandište', SerbianMunicipality.PLANDISTE],
    ['Babušnica', SerbianMunicipality.BABUSNICA],
];

function buildLocationAliasEntries(): [string, SerbianMunicipality][] {
    const merged = [...LOCATION_ALIAS_RAW, ...LOCATION_ALIAS_EXTRA];
    const seen = new Map<string, SerbianMunicipality>();
    for (const [raw, v] of merged) {
        const key = foldSerbianLatin(raw).replace(/\s+/g, ' ').trim();
        if (!key) continue;
        if (!seen.has(key)) seen.set(key, v);
    }
    return [...seen.entries()]
        .sort((a, b) => b[0].length - a[0].length || a[0].localeCompare(b[0]))
        .map(([k, v]) => [k, v] as [string, SerbianMunicipality]);
}

const LOCATION_ALIAS_ENTRIES: [string, SerbianMunicipality][] = buildLocationAliasEntries();

function matchesLocationAlias(folded: string, alias: string): boolean {
    const a = alias.trim();
    if (!a) return false;
    if (a.includes(' ')) return folded.includes(a);
    const re = new RegExp(`(^|[^a-z0-9])${escapeRegExp(a)}([^a-z0-9]|$)`);
    return re.test(folded);
}

/**
 * Resolve a municipality/city from free text, URL slug, or combined hints.
 * Longer alias matches win; single-token aliases use non-alphanumeric boundaries.
 */
export function resolveSerbianMunicipality(haystack: string): SerbianMunicipality {
    if (!haystack) return SerbianMunicipality.UNKNOWN;
    const folded = foldSerbianLatin(haystack).replace(/[_-]+/g, ' ');
    for (const [alias, value] of LOCATION_ALIAS_ENTRIES) {
        if (matchesLocationAlias(folded, alias)) return value;
    }
    return SerbianMunicipality.UNKNOWN;
}
